
/*
 * This file was generated by the SOM Compiler.
 * FileName: idl\wpstutor.h.
 * Generated using:
 *     SOM Precompiler somipc: 2.29.1.17
 *     SOM Emitter emith: 2.47
 */

/*
 * 
 *    Module Name: WPSTUTOR
 * 
 *    Description: OS/2 Work Place Shell Sample Program
 * 
 *                 This class subclasses the WPDataFile class.  Most WPS
 *                 instance and class methods are overridden to invoke
 *                 'DisplayMethodInfo'.  This function uses a named pipe
 *                 to communicate with the 'Show Method Description'
 *                 (SHOWDESC.EXE) program, which displays the name and a
 *                 description of the method that invoked
 *                 'DisplayMethodInfo'.
 * 
 *    Copyright (C) 1993 IBM Corporation
 * 
 *        DISCLAIMER OF WARRANTIES.  The following [enclosed] code is
 *        sample code created by IBM Corporation. This sample code is not
 *        part of any standard or IBM product and is provided to you solely
 *        for  the purpose of assisting you in the development of your
 *        applications.  The code is provided "AS IS", without
 *        warranty of any kind.  IBM shall not be liable for any damages
 *        arising out of your use of the sample code, even if they have been
 *        advised of the possibility of such damages.
 * 
 */


#ifndef SOM_WPSTutorial_h
#define SOM_WPSTutorial_h


#include <som.h>

/*
 * -- This emitter treats Method Tokens as Thunks by default.
 * -- Use the sc modifier "nothunks" to change this default
 */
#undef somresolve_
#define somresolve_(obj,mToken) ((somMethodProc*)((void)obj, mToken))

/*
 * Define the class name as an object type
 */
#ifndef WPSTutorial
#define WPSTutorial SOMObject
#endif
/*
 *  CLASS: WPSTutorial
 * 
 *  CLASS HIERARCHY:
 * 
 *      SOMObject
 *        ÀÄÄ WPObject
 *              ÀÄÄ WPFileSystem
 *                    ÀÄÄ WPDataFile
 *                          ÀÄÄ WPSTutorial
 * 
 *  DESCRIPTION:
 * 
 *     This is the sample WPS tutorial object class.  This class subclasses
 *     the WPDataFile class.  Most WPS instance and class methods are
 *     overridden to invoke 'DisplayMethodInfo'.  This function uses a named
 *     pipe to communicate with the 'Show Method Description' (SHOWDESC.EXE)
 *     program, which displays the name and a description of the method that
 *     invoked 'DisplayMethodInfo'.
 * 
 *     An instance of this class can be created as a Workplace object.
 * 
 */
#include <wpdataf.h>

/*
 * Start of bindings for IDL types
 */

#ifndef SOMClass
    #define SOMClass SOMObject
#endif /* SOMClass */
#ifndef WPFolder
    #define WPFolder SOMObject
#endif /* WPFolder */
#ifndef M_WPObject
    #define M_WPObject SOMObject
#endif /* M_WPObject */
#ifndef WPObject
    #define WPObject SOMObject
#endif /* WPObject */
#ifndef WPImageFile
    #define WPImageFile SOMObject
#endif /* WPImageFile */
#ifndef M_WPFileSystem
    #define M_WPFileSystem SOMObject
#endif /* M_WPFileSystem */
#ifndef M_WPDataFile
    #define M_WPDataFile SOMObject
#endif /* M_WPDataFile */
#ifndef M_WPSTutorial
    #define M_WPSTutorial SOMObject
#endif /* M_WPSTutorial */

/*
 * End of bindings for IDL types.
 */

#define WPSTutorial_MajorVersion 1
#define WPSTutorial_MinorVersion 1

/*
 * External name shortening if required
 */
#ifdef SOM_USE_SHORT_EXTERNAL_NAMES
#define WPSTutorialNewClass c
#pragma linkage(c, system)
#define WPSTutorialClassData d
#define WPSTutorialCClassData x
#endif /* SOM_USE_SHORT_EXTERNAL_NAMES */
/*--------------Migration------------*/
#define WPSTutorial_classObj WPSTutorialClassData.classObject
#define _WPSTutorial WPSTutorial_classObj

/*
 * Declare the class creation procedure
 */
SOMEXTERN SOMClass * SOMLINK WPSTutorialNewClass(integer4 somtmajorVersion,
		integer4 somtminorVersion);
#pragma linkage(WPSTutorialNewClass, system)

/*
 * Declare the class data structure
 */
SOMEXTERN struct WPSTutorialClassDataStructure {
	SOMClass *classObject;
	somMToken DisplayTitleInfo;
} SOMDLINK WPSTutorialClassData;

/*
 * Declare the C specific class data structure
 */
SOMEXTERN struct WPSTutorialCClassDataStructure {
	somMethodTabs parentMtab;
	somDToken instanceDataToken;
} SOMDLINK WPSTutorialCClassData;

/*
 * New and Renew macros for WPSTutorial
 */
#define WPSTutorialNew() \
   ( _WPSTutorial ? \
	_somNew(_WPSTutorial) \
	: ( WPSTutorialNewClass(\
		WPSTutorial_MajorVersion, \
		WPSTutorial_MinorVersion),\
	   _somNew(_WPSTutorial)))
#define WPSTutorialRenew(buf) \
   ( _WPSTutorial ? \
	_somRenew(_WPSTutorial, buf) \
	: ( WPSTutorialNewClass(\
		WPSTutorial_MajorVersion, \
		WPSTutorial_MinorVersion),\
	   _somRenew(_WPSTutorial, buf)))

/*
 * Override method: wpAddFileMenuPage
 */
#define WPSTutorial_wpAddFileMenuPage(somSelf,hwndNotebook) \
	WPFileSystem_wpAddFileMenuPage(somSelf,hwndNotebook)

/*
 * Override method: wpAddFileTypePage
 */
#define WPSTutorial_wpAddFileTypePage(somSelf,hwndNotebook) \
	WPDataFile_wpAddFileTypePage(somSelf,hwndNotebook)

/*
 * Override method: wpAddFile1Page
 */
#define WPSTutorial_wpAddFile1Page(somSelf,hwndNotebook) \
	WPFileSystem_wpAddFile1Page(somSelf,hwndNotebook)

/*
 * Override method: wpAddFile2Page
 */
#define WPSTutorial_wpAddFile2Page(somSelf,hwndNotebook) \
	WPFileSystem_wpAddFile2Page(somSelf,hwndNotebook)

/*
 * Override method: wpAddFile3Page
 */
#define WPSTutorial_wpAddFile3Page(somSelf,hwndNotebook) \
	WPFileSystem_wpAddFile3Page(somSelf,hwndNotebook)

/*
 * Override method: wpAddObjectGeneralPage
 */
#define WPSTutorial_wpAddObjectGeneralPage(somSelf,hwndNotebook) \
	WPObject_wpAddObjectGeneralPage(somSelf,hwndNotebook)

/*
 * Override method: wpAddSettingsPages
 */
#define WPSTutorial_wpAddSettingsPages(somSelf,hwndNotebook) \
	WPObject_wpAddSettingsPages(somSelf,hwndNotebook)

/*
 * Override method: wpAddToObjUseList
 */
#define WPSTutorial_wpAddToObjUseList(somSelf,pUseItem) \
	WPObject_wpAddToObjUseList(somSelf,pUseItem)

/*
 * Override method: wpAllocMem
 */
#define WPSTutorial_wpAllocMem(somSelf,cbBytes,prc) \
	WPObject_wpAllocMem(somSelf,cbBytes,prc)

/*
 * Override method: wpClose
 */
#define WPSTutorial_wpClose(somSelf) \
	WPObject_wpClose(somSelf)

/*
 * Override method: wpCopiedFromTemplate
 */
#define WPSTutorial_wpCopiedFromTemplate(somSelf) \
	WPObject_wpCopiedFromTemplate(somSelf)

/*
 * Override method: wpCopyObject
 */
#define WPSTutorial_wpCopyObject(somSelf,Folder,fLock) \
	WPObject_wpCopyObject(somSelf,Folder,fLock)

/*
 * Override method: wpCreateFromTemplate
 */
#define WPSTutorial_wpCreateFromTemplate(somSelf,folder,fLock) \
	WPObject_wpCreateFromTemplate(somSelf,folder,fLock)

/*
 * Override method: wpCreateShadowObject
 */
#define WPSTutorial_wpCreateShadowObject(somSelf,Folder,fLock) \
	WPObject_wpCreateShadowObject(somSelf,Folder,fLock)

/*
 * Override method: wpDelete
 */
#define WPSTutorial_wpDelete(somSelf,fConfirmations) \
	WPObject_wpDelete(somSelf,fConfirmations)

/*
 * Override method: wpDeleteFromObjUseList
 */
#define WPSTutorial_wpDeleteFromObjUseList(somSelf,pUseItem) \
	WPObject_wpDeleteFromObjUseList(somSelf,pUseItem)

/*
 * Override method: wpDoesObjectMatch
 */
#define WPSTutorial_wpDoesObjectMatch(somSelf,pvoidExtendedCriteria) \
	WPObject_wpDoesObjectMatch(somSelf,pvoidExtendedCriteria)

/*
 * Override method: wpDraggedOverObject
 */
#define WPSTutorial_wpDraggedOverObject(somSelf,DraggedOverObject) \
	WPObject_wpDraggedOverObject(somSelf,DraggedOverObject)

/*
 * Override method: wpDragOver
 */
#define WPSTutorial_wpDragOver(somSelf,hwndCnr,pdrgInfo) \
	WPObject_wpDragOver(somSelf,hwndCnr,pdrgInfo)

/*
 * Override method: wpDrop
 */
#define WPSTutorial_wpDrop(somSelf,hwndCnr,pdrgInfo,pdrgItem) \
	WPObject_wpDrop(somSelf,hwndCnr,pdrgInfo,pdrgItem)

/*
 * Override method: wpDroppedOnObject
 */
#define WPSTutorial_wpDroppedOnObject(somSelf,DroppedOnObject) \
	WPObject_wpDroppedOnObject(somSelf,DroppedOnObject)

/*
 * Override method: wpEndConversation
 */
#define WPSTutorial_wpEndConversation(somSelf,ulItemID,flResult) \
	WPObject_wpEndConversation(somSelf,ulItemID,flResult)

/*
 * Override method: wpFilterPopupMenu
 */
#define WPSTutorial_wpFilterPopupMenu(somSelf,ulFlags,hwndCnr,fMultiSelect) \
	WPObject_wpFilterPopupMenu(somSelf,ulFlags,hwndCnr,fMultiSelect)

/*
 * Override method: wpFindUseItem
 */
#define WPSTutorial_wpFindUseItem(somSelf,type,pCurrentItem) \
	WPObject_wpFindUseItem(somSelf,type,pCurrentItem)

/*
 * Override method: wpFormatDragItem
 */
#define WPSTutorial_wpFormatDragItem(somSelf,pdrgItem) \
	WPObject_wpFormatDragItem(somSelf,pdrgItem)

/*
 * Override method: wpFree
 */
#define WPSTutorial_wpFree(somSelf) \
	WPObject_wpFree(somSelf)

/*
 * Override method: wpFreeMem
 */
#define WPSTutorial_wpFreeMem(somSelf,pByte) \
	WPObject_wpFreeMem(somSelf,pByte)

/*
 * Override method: wpHide
 */
#define WPSTutorial_wpHide(somSelf) \
	WPObject_wpHide(somSelf)

/*
 * Override method: wpInitData
 */
#define WPSTutorial_wpInitData(somSelf) \
	WPObject_wpInitData(somSelf)

/*
 * Override method: wpInsertPopupMenuItems
 */
#define WPSTutorial_wpInsertPopupMenuItems(somSelf,hwndMenu,iPosition,hmod,MenuID,SubMenuID) \
	WPObject_wpInsertPopupMenuItems(somSelf,hwndMenu,iPosition,hmod,MenuID,SubMenuID)

/*
 * Override method: wpInsertSettingsPage
 */
#define WPSTutorial_wpInsertSettingsPage(somSelf,hwndNotebook,ppageinfo) \
	WPObject_wpInsertSettingsPage(somSelf,hwndNotebook,ppageinfo)

/*
 * Override method: wpMenuItemSelected
 */
#define WPSTutorial_wpMenuItemSelected(somSelf,hwndFrame,ulMenuId) \
	WPObject_wpMenuItemSelected(somSelf,hwndFrame,ulMenuId)

/*
 * Override method: wpModifyPopupMenu
 */
#define WPSTutorial_wpModifyPopupMenu(somSelf,hwndMenu,hwndCnr,iPosition) \
	WPObject_wpModifyPopupMenu(somSelf,hwndMenu,hwndCnr,iPosition)

/*
 * Override method: wpOpen
 */
#define WPSTutorial_wpOpen(somSelf,hwndCnr,ulView,param) \
	WPObject_wpOpen(somSelf,hwndCnr,ulView,param)

/*
 * Override method: wpQueryConfirmations
 */
#define WPSTutorial_wpQueryConfirmations(somSelf) \
	WPObject_wpQueryConfirmations(somSelf)

/*
 * Override method: wpQueryDefaultView
 */
#define WPSTutorial_wpQueryDefaultView(somSelf) \
	WPObject_wpQueryDefaultView(somSelf)

/*
 * Override method: wpQueryDetailsData
 */
#define WPSTutorial_wpQueryDetailsData(somSelf,ppDetailsData,pcp) \
	WPObject_wpQueryDetailsData(somSelf,ppDetailsData,pcp)

/*
 * Override method: wpQueryHandle
 */
#define WPSTutorial_wpQueryHandle(somSelf) \
	WPObject_wpQueryHandle(somSelf)

/*
 * Override method: wpQueryIcon
 */
#define WPSTutorial_wpQueryIcon(somSelf) \
	WPObject_wpQueryIcon(somSelf)

/*
 * Override method: wpQueryIconData
 */
#define WPSTutorial_wpQueryIconData(somSelf,pIconInfo) \
	WPObject_wpQueryIconData(somSelf,pIconInfo)

/*
 * Override method: wpQueryRealName
 */
#define WPSTutorial_wpQueryRealName(somSelf,pszFilename,pcb,fQualified) \
	WPFileSystem_wpQueryRealName(somSelf,pszFilename,pcb,fQualified)

/*
 * Override method: wpQueryStyle
 */
#define WPSTutorial_wpQueryStyle(somSelf) \
	WPObject_wpQueryStyle(somSelf)

/*
 * Override method: wpQueryTitle
 */
#define WPSTutorial_wpQueryTitle(somSelf) \
	WPObject_wpQueryTitle(somSelf)

/*
 * Override method: wpQueryType
 */
#define WPSTutorial_wpQueryType(somSelf) \
	WPFileSystem_wpQueryType(somSelf)

/*
 * Override method: wpRegisterView
 */
#define WPSTutorial_wpRegisterView(somSelf,hwndFrame,pszViewTitle) \
	WPObject_wpRegisterView(somSelf,hwndFrame,pszViewTitle)

/*
 * Override method: wpRender
 */
#define WPSTutorial_wpRender(somSelf,pdxfer) \
	WPObject_wpRender(somSelf,pdxfer)

/*
 * Override method: wpRenderComplete
 */
#define WPSTutorial_wpRenderComplete(somSelf,pdxfer,ulResult) \
	WPObject_wpRenderComplete(somSelf,pdxfer,ulResult)

/*
 * Override method: wpRestore
 */
#define WPSTutorial_wpRestore(somSelf) \
	WPObject_wpRestore(somSelf)

/*
 * Override method: wpRestoreData
 */
#define WPSTutorial_wpRestoreData(somSelf,pszClass,ulKey,pValue,pcbValue) \
	WPObject_wpRestoreData(somSelf,pszClass,ulKey,pValue,pcbValue)

/*
 * Override method: wpRestoreLong
 */
#define WPSTutorial_wpRestoreLong(somSelf,pszClass,ulKey,pulValue) \
	WPObject_wpRestoreLong(somSelf,pszClass,ulKey,pulValue)

/*
 * Override method: wpRestoreState
 */
#define WPSTutorial_wpRestoreState(somSelf,ulReserved) \
	WPObject_wpRestoreState(somSelf,ulReserved)

/*
 * Override method: wpRestoreString
 */
#define WPSTutorial_wpRestoreString(somSelf,pszClass,ulKey,pszValue,pcbValue) \
	WPObject_wpRestoreString(somSelf,pszClass,ulKey,pszValue,pcbValue)

/*
 * Override method: wpSaveData
 */
#define WPSTutorial_wpSaveData(somSelf,pszClass,ulKey,pValue,cbValue) \
	WPObject_wpSaveData(somSelf,pszClass,ulKey,pValue,cbValue)

/*
 * Override method: wpSaveDeferred
 */
#define WPSTutorial_wpSaveDeferred(somSelf) \
	WPObject_wpSaveDeferred(somSelf)

/*
 * Override method: wpSaveImmediate
 */
#define WPSTutorial_wpSaveImmediate(somSelf) \
	WPObject_wpSaveImmediate(somSelf)

/*
 * Override method: wpSaveLong
 */
#define WPSTutorial_wpSaveLong(somSelf,pszClass,ulKey,ulValue) \
	WPObject_wpSaveLong(somSelf,pszClass,ulKey,ulValue)

/*
 * Override method: wpSaveState
 */
#define WPSTutorial_wpSaveState(somSelf) \
	WPObject_wpSaveState(somSelf)

/*
 * Override method: wpSaveString
 */
#define WPSTutorial_wpSaveString(somSelf,pszClass,ulKey,pszValue) \
	WPObject_wpSaveString(somSelf,pszClass,ulKey,pszValue)

/*
 * Override method: wpSetDefaultView
 */
#define WPSTutorial_wpSetDefaultView(somSelf,ulView) \
	WPObject_wpSetDefaultView(somSelf,ulView)

/*
 * Override method: wpSetIcon
 */
#define WPSTutorial_wpSetIcon(somSelf,hptrNewIcon) \
	WPObject_wpSetIcon(somSelf,hptrNewIcon)

/*
 * Override method: wpSetIconData
 */
#define WPSTutorial_wpSetIconData(somSelf,pIconInfo) \
	WPObject_wpSetIconData(somSelf,pIconInfo)

/*
 * Override method: wpSetRealName
 */
#define WPSTutorial_wpSetRealName(somSelf,pszName) \
	WPFileSystem_wpSetRealName(somSelf,pszName)

/*
 * Override method: wpSetStyle
 */
#define WPSTutorial_wpSetStyle(somSelf,ulNewStyle) \
	WPObject_wpSetStyle(somSelf,ulNewStyle)

/*
 * Override method: wpSetTitle
 */
#define WPSTutorial_wpSetTitle(somSelf,pszNewTitle) \
	WPObject_wpSetTitle(somSelf,pszNewTitle)

/*
 * Override method: wpSetType
 */
#define WPSTutorial_wpSetType(somSelf,pszTypes,pfeal) \
	WPFileSystem_wpSetType(somSelf,pszTypes,pfeal)

/*
 * Override method: wpSetup
 */
#define WPSTutorial_wpSetup(somSelf,pszSetupString) \
	WPObject_wpSetup(somSelf,pszSetupString)

/*
 * Override method: wpSwitchTo
 */
#define WPSTutorial_wpSwitchTo(somSelf,View) \
	WPObject_wpSwitchTo(somSelf,View)

/*
 * Override method: wpUnlockObject
 */
#define WPSTutorial_wpUnlockObject(somSelf) \
	WPObject_wpUnlockObject(somSelf)

/*
 * Override method: wpUnInitData
 */
#define WPSTutorial_wpUnInitData(somSelf) \
	WPObject_wpUnInitData(somSelf)

/*
 * New Method: DisplayTitleInfo
 */
typedef HWND   SOMLINK somTP_WPSTutorial_DisplayTitleInfo(WPSTutorial *somSelf);
#pragma linkage(somTP_WPSTutorial_DisplayTitleInfo, system)
typedef somTP_WPSTutorial_DisplayTitleInfo *somTD_WPSTutorial_DisplayTitleInfo;
/*
 *  METHOD: DisplayTitleInfo                               ( ) PRIVATE
 *                                                         (X) PUBLIC
 *  DESCRIPTION:
 * 
 *    This method handles the processing of the "Open tutorial" menu item
 *    in the "Open" menu of the object's context menu.  The method creates a
 *    PM window in order to display the (backwards) title of the object in
 *    the window's title bar.
 * 
 *  RETURN:
 * 
 *    HWND - Handle to the window created
 * 
 */
#define somMD_WPSTutorial_DisplayTitleInfo "::WPSTutorial::DisplayTitleInfo"
#define WPSTutorial_DisplayTitleInfo(somSelf) \
    (SOM_Resolve(somSelf, WPSTutorial, DisplayTitleInfo) \
	(somSelf))
#ifndef SOMGD_DisplayTitleInfo
    #if (defined(_DisplayTitleInfo) || defined(__DisplayTitleInfo))
        #undef _DisplayTitleInfo
        #undef __DisplayTitleInfo
        #define SOMGD_DisplayTitleInfo 1
    #else
        #define _DisplayTitleInfo WPSTutorial_DisplayTitleInfo
    #endif /* _DisplayTitleInfo */
#endif /* SOMGD_DisplayTitleInfo */
#ifndef SOM_DONT_USE_INHERITED_MACROS
#define WPSTutorial_wpAddBecomePage WPDataFile_wpAddBecomePage
#define WPSTutorial_wpPrintMetaFile WPDataFile_wpPrintMetaFile
#define WPSTutorial_wpPrintPifFile WPDataFile_wpPrintPifFile
#define WPSTutorial_wpPrintPrinterSpecificFile WPDataFile_wpPrintPrinterSpecificFile
#define WPSTutorial_wpPrintUnknownFile WPDataFile_wpPrintUnknownFile
#define WPSTutorial_wpQueryAssociatedProgram WPDataFile_wpQueryAssociatedProgram
#define WPSTutorial_wpSetAssociatedFileIcon WPDataFile_wpSetAssociatedFileIcon
#define WPSTutorial_wpQueryAssociatedFileIcon WPDataFile_wpQueryAssociatedFileIcon
#define WPSTutorial_wpSetContentsFromPointer WPDataFile_wpSetContentsFromPointer
#define WPSTutorial_wpQueryPointerFromContents WPDataFile_wpQueryPointerFromContents
#define WPSTutorial_wpSetContentsFromHandle WPDataFile_wpSetContentsFromHandle
#define WPSTutorial_wpQueryHandleFromContents WPDataFile_wpQueryHandleFromContents
#define WPSTutorial_wpRenderFromClipboard WPDataFile_wpRenderFromClipboard
#define WPSTutorial_SetUpdateIndicator WPDataFile_SetUpdateIndicator
#define WPSTutorial_QueryUpdateIndicator WPDataFile_QueryUpdateIndicator
#define WPSTutorial_SetNeedSave WPDataFile_SetNeedSave
#define WPSTutorial_QueryNeedSave WPDataFile_QueryNeedSave
#define WPSTutorial_wpSetDefaultBidiSettings WPDataFile_wpSetDefaultBidiSettings
#define WPSTutorial_wpQueryDefaultBidiSettings WPDataFile_wpQueryDefaultBidiSettings
#define WPSTutorial_wpSetBidiValues WPDataFile_wpSetBidiValues
#define WPSTutorial_wpQueryBidiValues WPDataFile_wpQueryBidiValues
#define WPSTutorial_wpInsertBidiPage WPDataFile_wpInsertBidiPage
#define WPSTutorial_wpSaveBidiState WPDataFile_wpSaveBidiState
#define WPSTutorial_wpRestoreBidiState WPDataFile_wpRestoreBidiState
#define WPSTutorial_wpInitBidiData WPDataFile_wpInitBidiData
#define WPSTutorial_wpBidiSetup WPDataFile_wpBidiSetup
#define WPSTutorial_wpSettingsNotebook WPDataFile_wpSettingsNotebook
#define WPSTutorial_wpAddObjectWindowPage WPObject_wpAddObjectWindowPage
#define WPSTutorial_wpPrintObject WPObject_wpPrintObject
#define WPSTutorial_wpModifyMenu WPObject_wpModifyMenu
#define WPSTutorial_wpMenuItemHelpSelected WPObject_wpMenuItemHelpSelected
#define WPSTutorial_wpQueryDefaultHelp WPObject_wpQueryDefaultHelp
#define WPSTutorial_wpConfirmRenameFileWithExt WPFileSystem_wpConfirmRenameFileWithExt
#define WPSTutorial_somDefaultInit SOMObject_somDefaultInit
#define WPSTutorial_somDestruct SOMObject_somDestruct
#define WPSTutorial_wpConfirmKeepAssoc WPFileSystem_wpConfirmKeepAssoc
#define WPSTutorial_wpSetAttr WPFileSystem_wpSetAttr
#define WPSTutorial_wpQueryAttr WPFileSystem_wpQueryAttr
#define WPSTutorial_wpQueryCreation WPFileSystem_wpQueryCreation
#define WPSTutorial_wpQueryLastAccess WPFileSystem_wpQueryLastAccess
#define WPSTutorial_wpQueryLastWrite WPFileSystem_wpQueryLastWrite
#define WPSTutorial_wpQueryFileSize WPFileSystem_wpQueryFileSize
#define WPSTutorial_wpQueryEASize WPFileSystem_wpQueryEASize
#define WPSTutorial_wpSetDateInfo WPFileSystem_wpSetDateInfo
#define WPSTutorial_wpSetFileSizeInfo WPFileSystem_wpSetFileSizeInfo
#define WPSTutorial_wpRefresh WPFileSystem_wpRefresh
#define WPSTutorial_wpQueryRefreshFlags WPFileSystem_wpQueryRefreshFlags
#define WPSTutorial_wpSetRefreshFlags WPFileSystem_wpSetRefreshFlags
#define WPSTutorial_wpPrintPlainTextFile WPFileSystem_wpPrintPlainTextFile
#define WPSTutorial_wpSetTitleAndRenameFile WPFileSystem_wpSetTitleAndRenameFile
#define WPSTutorial_wpVerifyUpdateAccess WPFileSystem_wpVerifyUpdateAccess
#define WPSTutorial_wpQueryEASupport WPFileSystem_wpQueryEASupport
#define WPSTutorial_wpAddUserItemsToPopupMenu WPFileSystem_wpAddUserItemsToPopupMenu
#define WPSTutorial_wpIsDiskSwapped WPFileSystem_wpIsDiskSwapped
#define WPSTutorial_wpQueryFilename WPFileSystem_wpQueryFilename
#define WPSTutorial_wpQueryDisk WPFileSystem_wpQueryDisk
#define WPSTutorial_wpQueryDateInfo WPFileSystem_wpQueryDateInfo
#define WPSTutorial_wpQueryFileSizeL WPFileSystem_wpQueryFileSizeL
#define WPSTutorial_wpSetFileSizeL WPFileSystem_wpSetFileSizeL
#define WPSTutorial_wpViewObject WPObject_wpViewObject
#define WPSTutorial_wpMoveObject WPObject_wpMoveObject
#define WPSTutorial_wpQueryNameClashOptions WPObject_wpQueryNameClashOptions
#define WPSTutorial_wpAppendObject WPObject_wpAppendObject
#define WPSTutorial_wpReplaceObject WPObject_wpReplaceObject
#define WPSTutorial_wpFilterMenu WPObject_wpFilterMenu
#define WPSTutorial_wpIdentify WPObject_wpIdentify
#define WPSTutorial_wpIsDeleteable WPObject_wpIsDeleteable
#define WPSTutorial_wpAddObjectGeneralPage2 WPObject_wpAddObjectGeneralPage2
#define WPSTutorial_wpAssertObjectMutexSem WPObject_wpAssertObjectMutexSem
#define WPSTutorial_wpCnrInsertObject WPObject_wpCnrInsertObject
#define WPSTutorial_wpCnrRemoveObject WPObject_wpCnrRemoveObject
#define WPSTutorial_wpCnrSetEmphasis WPObject_wpCnrSetEmphasis
#define WPSTutorial_wpConfirmDelete WPObject_wpConfirmDelete
#define WPSTutorial_wpConfirmObjectTitle WPObject_wpConfirmObjectTitle
#define WPSTutorial_wpCreateAnother WPObject_wpCreateAnother
#define WPSTutorial_wpDisplayHelp WPObject_wpDisplayHelp
#define WPSTutorial_wpDisplayMenu WPObject_wpDisplayMenu
#define WPSTutorial_wpInsertMenuItems WPObject_wpInsertMenuItems
#define WPSTutorial_wpQueryConcurrentView WPObject_wpQueryConcurrentView
#define WPSTutorial_wpQueryButtonAppearance WPObject_wpQueryButtonAppearance
#define WPSTutorial_wpQueryError WPObject_wpQueryError
#define WPSTutorial_wpSetFolder WPObject_wpSetFolder
#define WPSTutorial_wpQueryFolder WPObject_wpQueryFolder
#define WPSTutorial_wpQueryMinWindow WPObject_wpQueryMinWindow
#define WPSTutorial_wpSetTaskRec WPObject_wpSetTaskRec
#define WPSTutorial_wpFindTaskRec WPObject_wpFindTaskRec
#define WPSTutorial_wpReleaseObjectMutexSem WPObject_wpReleaseObjectMutexSem
#define WPSTutorial_wpRequestObjectMutexSem WPObject_wpRequestObjectMutexSem
#define WPSTutorial_wpScanSetupString WPObject_wpScanSetupString
#define WPSTutorial_wpSetConcurrentView WPObject_wpSetConcurrentView
#define WPSTutorial_wpSetButtonAppearance WPObject_wpSetButtonAppearance
#define WPSTutorial_wpSetDefaultHelp WPObject_wpSetDefaultHelp
#define WPSTutorial_wpSetError WPObject_wpSetError
#define WPSTutorial_wpQueryScreenGroupID WPObject_wpQueryScreenGroupID
#define WPSTutorial_wpSetupOnce WPObject_wpSetupOnce
#define WPSTutorial_wpSetMinWindow WPObject_wpSetMinWindow
#define WPSTutorial_wpModifyStyle WPObject_wpModifyStyle
#define WPSTutorial_wpQueryTrueStyle WPObject_wpQueryTrueStyle
#define WPSTutorial_wpObjectReady WPObject_wpObjectReady
#define WPSTutorial_wpIsObjectInitialized WPObject_wpIsObjectInitialized
#define WPSTutorial_wpCreateShadowObjectExt WPObject_wpCreateShadowObjectExt
#define WPSTutorial_wpCnrDeleteUseItem WPObject_wpCnrDeleteUseItem
#define WPSTutorial_wpQueryCoreRecord WPObject_wpQueryCoreRecord
#define WPSTutorial_wpSetObjectID WPObject_wpSetObjectID
#define WPSTutorial_wpQueryObjectID WPObject_wpQueryObjectID
#define WPSTutorial_wpSetDefaultIconPos WPObject_wpSetDefaultIconPos
#define WPSTutorial_wpQueryDefaultIconPos WPObject_wpQueryDefaultIconPos
#define WPSTutorial_wpCnrRefreshDetails WPObject_wpCnrRefreshDetails
#define WPSTutorial_wpFindViewItem WPObject_wpFindViewItem
#define WPSTutorial_wpLockObject WPObject_wpLockObject
#define WPSTutorial_wpIsLocked WPObject_wpIsLocked
#define WPSTutorial_wpQueryContainerFlagPtr WPObject_wpQueryContainerFlagPtr
#define WPSTutorial_wpWaitForClose WPObject_wpWaitForClose
#define WPSTutorial_wpSetMenuStyle WPObject_wpSetMenuStyle
#define WPSTutorial_wpQueryMenuStyle WPObject_wpQueryMenuStyle
#define WPSTutorial_somInit SOMObject_somInit
#define WPSTutorial_somUninit SOMObject_somUninit
#define WPSTutorial_somDefaultCopyInit SOMObject_somDefaultCopyInit
#define WPSTutorial_somDefaultAssign SOMObject_somDefaultAssign
#define WPSTutorial_somDefaultConstCopyInit SOMObject_somDefaultConstCopyInit
#define WPSTutorial_somDefaultVCopyInit SOMObject_somDefaultVCopyInit
#define WPSTutorial_somDefaultConstVCopyInit SOMObject_somDefaultConstVCopyInit
#define WPSTutorial_somDefaultConstAssign SOMObject_somDefaultConstAssign
#define WPSTutorial_somDefaultVAssign SOMObject_somDefaultVAssign
#define WPSTutorial_somDefaultConstVAssign SOMObject_somDefaultConstVAssign
#define WPSTutorial_somFree SOMObject_somFree
#define WPSTutorial_somGetClass SOMObject_somGetClass
#define WPSTutorial_somGetClassName SOMObject_somGetClassName
#define WPSTutorial_somGetSize SOMObject_somGetSize
#define WPSTutorial_somIsA SOMObject_somIsA
#define WPSTutorial_somIsInstanceOf SOMObject_somIsInstanceOf
#define WPSTutorial_somRespondsTo SOMObject_somRespondsTo
#define WPSTutorial_somDispatch SOMObject_somDispatch
#define WPSTutorial_somClassDispatch SOMObject_somClassDispatch
#define WPSTutorial_somCastObj SOMObject_somCastObj
#define WPSTutorial_somResetObj SOMObject_somResetObj
#define WPSTutorial_somDispatchV SOMObject_somDispatchV
#define WPSTutorial_somDispatchL SOMObject_somDispatchL
#define WPSTutorial_somDispatchA SOMObject_somDispatchA
#define WPSTutorial_somDispatchD SOMObject_somDispatchD
#define WPSTutorial_somPrintSelf SOMObject_somPrintSelf
#define WPSTutorial_somDumpSelf SOMObject_somDumpSelf
#define WPSTutorial_somDumpSelfInt SOMObject_somDumpSelfInt
#endif /* SOM_DONT_USE_INHERITED_MACROS */

#endif       /* SOM_WPSTutorial_h */

#ifndef SOM_M_WPSTutorial_h
#define SOM_M_WPSTutorial_h


#include <som.h>

/*
 * -- This emitter treats Method Tokens as Thunks by default.
 * -- Use the sc modifier "nothunks" to change this default
 */
#undef somresolve_
#define somresolve_(obj,mToken) ((somMethodProc*)((void)obj, mToken))

/*
 * Define the class name as an object type
 */
#ifndef M_WPSTutorial
#define M_WPSTutorial SOMObject
#endif
#include <wpdataf.h>

/*
 * Start of bindings for IDL types
 */


/*
 * End of bindings for IDL types.
 */

#define M_WPSTutorial_MajorVersion 1
#define M_WPSTutorial_MinorVersion 1

/*
 * External name shortening if required
 */
#ifdef SOM_USE_SHORT_EXTERNAL_NAMES
#define M_WPSTutorialNewClass c
#pragma linkage(c, system)
#define M_WPSTutorialClassData d
#define M_WPSTutorialCClassData x
#endif /* SOM_USE_SHORT_EXTERNAL_NAMES */
/*--------------Migration------------*/
#define M_WPSTutorial_classObj M_WPSTutorialClassData.classObject
#define _M_WPSTutorial M_WPSTutorial_classObj

/*
 * Declare the class creation procedure
 */
SOMEXTERN SOMClass * SOMLINK M_WPSTutorialNewClass(integer4 somtmajorVersion,
		integer4 somtminorVersion);
#pragma linkage(M_WPSTutorialNewClass, system)

/*
 * Declare the class data structure
 */
SOMEXTERN struct M_WPSTutorialClassDataStructure {
	SOMClass *classObject;
	somMToken clsQueryModuleHandle;
} SOMDLINK M_WPSTutorialClassData;

/*
 * Declare the C specific class data structure
 */
SOMEXTERN struct M_WPSTutorialCClassDataStructure {
	somMethodTabs parentMtab;
	somDToken instanceDataToken;
} SOMDLINK M_WPSTutorialCClassData;

/*
 * New and Renew macros for M_WPSTutorial
 */
#define M_WPSTutorialNew() \
   ( _M_WPSTutorial ? \
	_somNew(_M_WPSTutorial) \
	: ( M_WPSTutorialNewClass(\
		M_WPSTutorial_MajorVersion, \
		M_WPSTutorial_MinorVersion),\
	   _somNew(_M_WPSTutorial)))
#define M_WPSTutorialRenew(buf) \
   ( _M_WPSTutorial ? \
	_somRenew(_M_WPSTutorial, buf) \
	: ( M_WPSTutorialNewClass(\
		M_WPSTutorial_MajorVersion, \
		M_WPSTutorial_MinorVersion),\
	   _somRenew(_M_WPSTutorial, buf)))

/*
 * Override method: wpclsCreateDefaultTemplates
 */
#define M_WPSTutorial_wpclsCreateDefaultTemplates(somSelf,Folder) \
	M_WPObject_wpclsCreateDefaultTemplates(somSelf,Folder)

/*
 * Override method: wpclsFindObjectEnd
 */
#define M_WPSTutorial_wpclsFindObjectEnd(somSelf,hFind) \
	M_WPObject_wpclsFindObjectEnd(somSelf,hFind)

/*
 * Override method: wpclsFindObjectFirst
 */
#define M_WPSTutorial_wpclsFindObjectFirst(somSelf,pClassList,phFind,pszTitle,Folder,fSubfolders,pExtendedCriteria,pBuffer,pCount) \
	M_WPObject_wpclsFindObjectFirst(somSelf,pClassList,phFind,pszTitle,Folder,fSubfolders,pExtendedCriteria,pBuffer,pCount)

/*
 * Override method: wpclsFindObjectNext
 */
#define M_WPSTutorial_wpclsFindObjectNext(somSelf,hFind,pBuffer,pCount) \
	M_WPObject_wpclsFindObjectNext(somSelf,hFind,pBuffer,pCount)

/*
 * Override method: wpclsInitData
 */
#define M_WPSTutorial_wpclsInitData(somSelf) \
	M_WPObject_wpclsInitData(somSelf)

/*
 * Override method: wpclsMakeAwake
 */
#define M_WPSTutorial_wpclsMakeAwake(somSelf,pszTitle,ulStyle,hptrIcon,pObjData,Folder,ulUser) \
	M_WPObject_wpclsMakeAwake(somSelf,pszTitle,ulStyle,hptrIcon,pObjData,Folder,ulUser)

/*
 * Override method: wpclsNew
 */
#define M_WPSTutorial_wpclsNew(somSelf,pszTitle,pszSetupEnv,Folder,fLock) \
	M_WPObject_wpclsNew(somSelf,pszTitle,pszSetupEnv,Folder,fLock)

/*
 * Override method: wpclsQueryDefaultView
 */
#define M_WPSTutorial_wpclsQueryDefaultView(somSelf) \
	M_WPObject_wpclsQueryDefaultView(somSelf)

/*
 * Override method: wpclsQueryDetails
 */
#define M_WPSTutorial_wpclsQueryDetails(somSelf) \
	M_WPObject_wpclsQueryDetails(somSelf)

/*
 * Override method: wpclsQueryDetailsInfo
 */
#define M_WPSTutorial_wpclsQueryDetailsInfo(somSelf,ppClassFieldInfo,pSize) \
	M_WPObject_wpclsQueryDetailsInfo(somSelf,ppClassFieldInfo,pSize)

/*
 * Override method: wpclsQueryFolder
 */
#define M_WPSTutorial_wpclsQueryFolder(somSelf,pszLocation,fLock) \
	M_WPObject_wpclsQueryFolder(somSelf,pszLocation,fLock)

/*
 * Override method: wpclsQueryIcon
 */
#define M_WPSTutorial_wpclsQueryIcon(somSelf) \
	M_WPObject_wpclsQueryIcon(somSelf)

/*
 * Override method: wpclsQueryIconData
 */
#define M_WPSTutorial_wpclsQueryIconData(somSelf,pIconInfo) \
	M_WPObject_wpclsQueryIconData(somSelf,pIconInfo)

/*
 * Override method: wpclsQueryInstanceFilter
 */
#define M_WPSTutorial_wpclsQueryInstanceFilter(somSelf) \
	M_WPFileSystem_wpclsQueryInstanceFilter(somSelf)

/*
 * Override method: wpclsQueryInstanceType
 */
#define M_WPSTutorial_wpclsQueryInstanceType(somSelf) \
	M_WPFileSystem_wpclsQueryInstanceType(somSelf)

/*
 * Override method: wpclsQueryObject
 */
#define M_WPSTutorial_wpclsQueryObject(somSelf,hObject) \
	M_WPObject_wpclsQueryObject(somSelf,hObject)

/*
 * Override method: wpclsQuerySettingsPageSize
 */
#define M_WPSTutorial_wpclsQuerySettingsPageSize(somSelf,pSizl) \
	M_WPObject_wpclsQuerySettingsPageSize(somSelf,pSizl)

/*
 * Override method: wpclsQueryStyle
 */
#define M_WPSTutorial_wpclsQueryStyle(somSelf) \
	M_WPObject_wpclsQueryStyle(somSelf)

/*
 * Override method: wpclsQueryTitle
 */
#define M_WPSTutorial_wpclsQueryTitle(somSelf) \
	M_WPObject_wpclsQueryTitle(somSelf)

/*
 * Override method: wpclsUnInitData
 */
#define M_WPSTutorial_wpclsUnInitData(somSelf) \
	M_WPObject_wpclsUnInitData(somSelf)

/*
 * New Method: clsQueryModuleHandle
 */
typedef HMODULE   SOMLINK somTP_M_WPSTutorial_clsQueryModuleHandle(M_WPSTutorial *somSelf);
#pragma linkage(somTP_M_WPSTutorial_clsQueryModuleHandle, system)
typedef somTP_M_WPSTutorial_clsQueryModuleHandle *somTD_M_WPSTutorial_clsQueryModuleHandle;
/*
 *  METHOD: clsQueryModuleHandle
 * 
 *  DESCRIPTION:
 * 
 *    This method obtains and returns the module handle for the object class.
 * 
 *  RETURN:
 * 
 *    0        - Unsuccessful execution
 *    Non-zero - Module handle
 * 
 */
#define somMD_M_WPSTutorial_clsQueryModuleHandle "::M_WPSTutorial::clsQueryModuleHandle"
#define M_WPSTutorial_clsQueryModuleHandle(somSelf) \
    (SOM_Resolve(somSelf, M_WPSTutorial, clsQueryModuleHandle) \
	(somSelf))
#ifndef SOMGD_clsQueryModuleHandle
    #if (defined(_clsQueryModuleHandle) || defined(__clsQueryModuleHandle))
        #undef _clsQueryModuleHandle
        #undef __clsQueryModuleHandle
        #define SOMGD_clsQueryModuleHandle 1
    #else
        #define _clsQueryModuleHandle M_WPSTutorial_clsQueryModuleHandle
    #endif /* _clsQueryModuleHandle */
#endif /* SOMGD_clsQueryModuleHandle */
#ifndef SOM_DONT_USE_INHERITED_MACROS
#define M_WPSTutorial_wpclsAddClipboardAssoc M_WPDataFile_wpclsAddClipboardAssoc
#define M_WPSTutorial_wpclsEnumClipboardClasses M_WPDataFile_wpclsEnumClipboardClasses
#define M_WPSTutorial_wpclsQueryDefaultHelp M_WPObject_wpclsQueryDefaultHelp
#define M_WPSTutorial_wpclsQueryAwakeObject M_WPFileSystem_wpclsQueryAwakeObject
#define M_WPSTutorial_wpclsFileSysExists M_WPFileSystem_wpclsFileSysExists
#define M_WPSTutorial_wpclsQueryObjectFromPath M_WPFileSystem_wpclsQueryObjectFromPath
#define M_WPSTutorial_wpclsQueryInstanceClass M_WPFileSystem_wpclsQueryInstanceClass
#define M_WPSTutorial_wpclsQuerySearchInfo M_WPObject_wpclsQuerySearchInfo
#define M_WPSTutorial_wpclsQueryExtendedCriteria M_WPObject_wpclsQueryExtendedCriteria
#define M_WPSTutorial_wpclsObjectFromHandle M_WPObject_wpclsObjectFromHandle
#define M_WPSTutorial_wpclsSetError M_WPObject_wpclsSetError
#define M_WPSTutorial_wpclsQueryError M_WPObject_wpclsQueryError
#define M_WPSTutorial_wpclsQueryButtonAppearance M_WPObject_wpclsQueryButtonAppearance
#define M_WPSTutorial_wpclsDecUsage M_WPObject_wpclsDecUsage
#define M_WPSTutorial_wpclsIncUsage M_WPObject_wpclsIncUsage
#define M_WPSTutorial_wpclsInsertMultipleObjects M_WPObject_wpclsInsertMultipleObjects
#define M_WPSTutorial_wpclsFindOneObject M_WPObject_wpclsFindOneObject
#define M_WPSTutorial_wpclsSetSettingsPageSize M_WPObject_wpclsSetSettingsPageSize
#define M_WPSTutorial_wpclsSetIconData M_WPObject_wpclsSetIconData
#define M_WPSTutorial_wpclsSetIcon M_WPObject_wpclsSetIcon
#define M_WPSTutorial_wpclsRemoveObjects M_WPObject_wpclsRemoveObjects
#define M_WPSTutorial_somUninit SOMObject_somUninit
#define M_WPSTutorial_somClassReady SOMClass_somClassReady
#define M_WPSTutorial_somNew SOMClass_somNew
#define M_WPSTutorial_somRenew SOMClass_somRenew
#define M_WPSTutorial__get_somDataAlignment SOMClass__get_somDataAlignment
#define M_WPSTutorial__get_somInstanceDataOffsets SOMClass__get_somInstanceDataOffsets
#define M_WPSTutorial__get_somDirectInitClasses SOMClass__get_somDirectInitClasses
#define M_WPSTutorial_somNewNoInit SOMClass_somNewNoInit
#define M_WPSTutorial_somRenewNoInit SOMClass_somRenewNoInit
#define M_WPSTutorial_somRenewNoZero SOMClass_somRenewNoZero
#define M_WPSTutorial_somRenewNoInitNoZero SOMClass_somRenewNoInitNoZero
#define M_WPSTutorial_somAllocate SOMClass_somAllocate
#define M_WPSTutorial_somDeallocate SOMClass_somDeallocate
#define M_WPSTutorial_somInitClass SOMClass_somInitClass
#define M_WPSTutorial_somInitMIClass SOMClass_somInitMIClass
#define M_WPSTutorial_somAddStaticMethod SOMClass_somAddStaticMethod
#define M_WPSTutorial_somAddDynamicMethod SOMClass_somAddDynamicMethod
#define M_WPSTutorial_somOverrideSMethod SOMClass_somOverrideSMethod
#define M_WPSTutorial_somGetApplyStub SOMClass_somGetApplyStub
#define M_WPSTutorial_somGetClassData SOMClass_somGetClassData
#define M_WPSTutorial_somSetClassData SOMClass_somSetClassData
#define M_WPSTutorial_somGetClassMtab SOMClass_somGetClassMtab
#define M_WPSTutorial_somGetInstanceOffset SOMClass_somGetInstanceOffset
#define M_WPSTutorial_somGetInstancePartSize SOMClass_somGetInstancePartSize
#define M_WPSTutorial_somGetInstanceSize SOMClass_somGetInstanceSize
#define M_WPSTutorial_somGetInstanceToken SOMClass_somGetInstanceToken
#define M_WPSTutorial_somGetMemberToken SOMClass_somGetMemberToken
#define M_WPSTutorial_somGetMethodData SOMClass_somGetMethodData
#define M_WPSTutorial_somGetRdStub SOMClass_somGetRdStub
#define M_WPSTutorial_somGetMethodDescriptor SOMClass_somGetMethodDescriptor
#define M_WPSTutorial_somGetMethodIndex SOMClass_somGetMethodIndex
#define M_WPSTutorial_somGetMethodToken SOMClass_somGetMethodToken
#define M_WPSTutorial_somGetName SOMClass_somGetName
#define M_WPSTutorial_somGetNthMethodData SOMClass_somGetNthMethodData
#define M_WPSTutorial_somGetNthMethodInfo SOMClass_somGetNthMethodInfo
#define M_WPSTutorial_somGetNumMethods SOMClass_somGetNumMethods
#define M_WPSTutorial_somGetNumStaticMethods SOMClass_somGetNumStaticMethods
#define M_WPSTutorial_somGetParent SOMClass_somGetParent
#define M_WPSTutorial_somGetParents SOMClass_somGetParents
#define M_WPSTutorial_somGetVersionNumbers SOMClass_somGetVersionNumbers
#define M_WPSTutorial_somFindMethod SOMClass_somFindMethod
#define M_WPSTutorial_somFindMethodOk SOMClass_somFindMethodOk
#define M_WPSTutorial_somFindSMethod SOMClass_somFindSMethod
#define M_WPSTutorial_somFindSMethodOk SOMClass_somFindSMethodOk
#define M_WPSTutorial_somLookupMethod SOMClass_somLookupMethod
#define M_WPSTutorial_somCheckVersion SOMClass_somCheckVersion
#define M_WPSTutorial_somDescendedFrom SOMClass_somDescendedFrom
#define M_WPSTutorial_somSupportsMethod SOMClass_somSupportsMethod
#define M_WPSTutorial_somDefinedMethod SOMClass_somDefinedMethod
#define M_WPSTutorial_somOverrideMtab SOMClass_somOverrideMtab
#define M_WPSTutorial_somDefaultInit SOMObject_somDefaultInit
#define M_WPSTutorial_somDestruct SOMObject_somDestruct
#define M_WPSTutorial_somDefaultCopyInit SOMObject_somDefaultCopyInit
#define M_WPSTutorial_somDefaultAssign SOMObject_somDefaultAssign
#define M_WPSTutorial_somDefaultConstCopyInit SOMObject_somDefaultConstCopyInit
#define M_WPSTutorial_somDefaultVCopyInit SOMObject_somDefaultVCopyInit
#define M_WPSTutorial_somDefaultConstVCopyInit SOMObject_somDefaultConstVCopyInit
#define M_WPSTutorial_somDefaultConstAssign SOMObject_somDefaultConstAssign
#define M_WPSTutorial_somDefaultVAssign SOMObject_somDefaultVAssign
#define M_WPSTutorial_somDefaultConstVAssign SOMObject_somDefaultConstVAssign
#define M_WPSTutorial_somInit SOMObject_somInit
#define M_WPSTutorial_somFree SOMObject_somFree
#define M_WPSTutorial_somGetClass SOMObject_somGetClass
#define M_WPSTutorial_somGetClassName SOMObject_somGetClassName
#define M_WPSTutorial_somGetSize SOMObject_somGetSize
#define M_WPSTutorial_somIsA SOMObject_somIsA
#define M_WPSTutorial_somIsInstanceOf SOMObject_somIsInstanceOf
#define M_WPSTutorial_somRespondsTo SOMObject_somRespondsTo
#define M_WPSTutorial_somDispatch SOMObject_somDispatch
#define M_WPSTutorial_somClassDispatch SOMObject_somClassDispatch
#define M_WPSTutorial_somCastObj SOMObject_somCastObj
#define M_WPSTutorial_somResetObj SOMObject_somResetObj
#define M_WPSTutorial_somDispatchV SOMObject_somDispatchV
#define M_WPSTutorial_somDispatchL SOMObject_somDispatchL
#define M_WPSTutorial_somDispatchA SOMObject_somDispatchA
#define M_WPSTutorial_somDispatchD SOMObject_somDispatchD
#define M_WPSTutorial_somPrintSelf SOMObject_somPrintSelf
#define M_WPSTutorial_somDumpSelf SOMObject_somDumpSelf
#define M_WPSTutorial_somDumpSelfInt SOMObject_somDumpSelfInt
#endif /* SOM_DONT_USE_INHERITED_MACROS */

#endif       /* SOM_M_WPSTutorial_h */
